name: Go Checks

on:
  pull_request:
    branches: [ "main","master" ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ "main","master" ]
  workflow_dispatch: {}

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Verify dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || \
            (echo "❌ go.mod or go.sum not tidy" && exit 1)

      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting (gofmt)
        run: |
          UNFORMATTED=$(gofmt -l .)
          if [ -n "$UNFORMATTED" ]; then
            echo "❌ Unformatted files:"
            echo "$UNFORMATTED"
            exit 1
          fi
          echo "✅ All files formatted"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...
